spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/resource_management?characterEncoding=utf-8&&useSSL=false
  jpa:
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    multipart:
      max-file-size: 1000Mb
      max-request-size: 1000Mb
server:
  port: 8082
mybatis:
  type-handlers-package: cn.edu.ujs.typehandler
#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
